refactor: restructure `bin` directory
Additions:
- Add `sh41-tui` script for exposing own UI primitives

Updates:
- Rename and relocate `prompt`, `send`, and `providers` scripts to
  `subcommands` directory
- Add internal utility dir to `PATH` for easy access in all other
  subcommands and scripts
- Consolidate error handling and debug trace across main script and subcommands

Removals:
- Remove `task` directory and its contents, will be restructured in
  future commits

diff --git a/bin/sh41 b/bin/sh41
--- a/bin/sh41
+++ b/bin/sh41
@@ -7,66 +7,74 @@
 #
 # ENVIROMENT
 #  SH41_BIN
-#   The path to the bin home directory.
+#   Path to SH41 public bin directory.
 #
-#  SH41_UTILS
-#   The path to the utilities home directory.
+#  SH41_LIB
+#   Path to SH41 internal lib directory.
 #
 #  SH41_ICON
 #   SH41 logo icon
 
+# ╭───┤ Dependencies
+# ╰─
+
+if ! command -v "jq" >/dev/null 2>&1; then
+  echo "sh41: jq is required to run this script" >&2
+  exit 1
+fi
+
+# ╭───┤ Bootstrap
+# ╰─
+
 # Exit on first error
 set -e
 
-# When printing an error's stack trace, use this process' parent id as the stop
-# point
-export SH41_ROOT_PID="${SH41_ROOT_PID:-$PPID}"
+# Expose all internal utility scripts for the duration of the process
+export PATH="$SH41_LIB/_scripts:$PATH"
 
-# ╭───┤ Unexpected exit traps
+# ╭───┤ Traps & Signals
 # ╰─
 
-debug_trace() {
+# trace-process goes up the call stack until TP_ROOT_PID is reached
+export TP_ROOT_PID="$PPID"
+# trace-process removes TP_BASE_PATH when logging
+export TP_BASE_PATH="$SH41_HOME"
+
+debug() {
   exit_code=$?; 
 
   if [ $exit_code -ne 0 ]; then
-    "$SH41_UTILS"/trace-process >&2
+    trace-process >&2
     exit $exit_code
   fi
 }
 
-trap debug_trace EXIT
-
-# ╭───┤ Global variables
-# ╰─
-
-CMD_NAME="sh41"
-
-# ╭───┤ Functions
-# ╰─
-
-# Redirect stdin from /dev/tty to ensure it's treated as interactive and not
-# inherited from parent's stdin
-log_error() { "$SH41_UTILS"/log "$@" "$CMD_NAME" < /dev/tty; }
+trap debug EXIT
 
 # ╭───┤ Main
 # ╰─
 
+subcommands_home="$SH41_BIN/subcommands"
+
 case $1 in
   prompt)
     shift
-    "$SH41_BIN"/sh41-prompt "$@" < /dev/stdin
-  ;;
+    "$subcommands_home"/prompt "$@" < /dev/stdin
+     ;;
   providers)
     shift
-    "$SH41_BIN"/sh41-provider "$@" < /dev/stdin
+    "$subcommands_home"/providers "$@" < /dev/stdin
   ;;
   send)
     shift
-    "$SH41_BIN"/sh41-prompt validate < /dev/stdin \
+    "$subcommands_home"/prompt validate < /dev/stdin \
       | if [ $? -eq 0 ]; then 
-          "$SH41_BIN"/sh41-send "$@"
+          "$subcommands_home"/send "$@"
         fi
     exit
   ;;
-  *) log_error "unknown argument $1"; exit 1 ;;
+  *) 
+    log -t error "unknown argument $1" "$SH41_ICON sh41"
+    exit 1 
+  ;;
 esac
