refactor: streamline logging and error handling across scripts
Updates:
- Standardize logging functions using `log` script, removing custom `log_error` functions
- Incorporate `LOG_NAMESPACE` for contextual logging across different script scopes such as `prompt`, `provider`, and examples
- Simplify the bootstrap and traps setup across scripts with more consistent source calling and environment setup

Removals:
- Remove unused variables and functions across various scripts, such as `CMD_NAME` in the `openai` provider script

diff --git a/lib/prompt/append b/lib/prompt/append
--- a/lib/prompt/append
+++ b/lib/prompt/append
@@ -28,22 +28,14 @@
 # SEE ALSO
 #  jq(1)
 
-# ╭───┤ Traps & Signals
+# ╭───┤ Bootstrap
 # ╰─
 
 # shellcheck source=../_fn/trap-debug
 . "$SH41_LIB/_fn/trap-debug"
 
-# ╭───┤ Functions
-# ╰─
-
-log_error() { 
-  log --type error "$@" "$SH41_ICON sh41-prompt-append"
-}
-
-log_info() {
-  log --type info "$@" "$SH41_ICON sh41-prompt-append"
-}
+# log config
+export LOG_NAMESPACE="$SH41_ICON sh41-prompt-append"
 
 # ╭───┤ Argument parsing
 # ╰─
@@ -57,7 +49,7 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         ROLE="$2"; shift
       else
-        log_error "-r|--role flag requires a value"
+        log error "-r|--role flag requires a value"
         exit 1
       fi
     ;;
@@ -65,7 +57,7 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         CONTENT="$2"; shift
       else
-        log_error "-c|--content flag requires a value"
+        log error "-c|--content flag requires a value"
         exit 1
       fi
     ;;
@@ -73,11 +65,11 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         FILE_PATH="$2"; shift
       else
-        log_error "-f|--file flag requires a value"
+        log error "-f|--file flag requires a value"
         exit 1
       fi
     ;;
-    *) log_error "unknown argument $1"; exit 1 ;;
+    *) log error "unknown argument $1"; exit 1 ;;
   esac
   shift
 done
@@ -86,22 +78,22 @@ done
 # ╰─
 
 if [ -z "$ROLE" ] && [ -z "$CONTENT" ] && [ -z "$FILE_PATH" ]; then
-  log_error "Missing required arguments, use either -r|--role and -c|--content or -f|--file"
+  log error "Missing required arguments, use either -r|--role and -c|--content or -f|--file"
   exit 1
 fi
 
 if { [ -n "$ROLE" ] || [ -n "$CONTENT" ]; } && [ -n "$FILE_PATH" ]; then
-  log_error "-r|--role and -c|--content cannot be used together with -f|--file"
+  log error "-r|--role and -c|--content cannot be used together with -f|--file"
   exit 1
 fi
 
 if { [ -n "$ROLE" ] && [ -z "$CONTENT" ]; } || { [ -z "$ROLE" ] && [ -n "$CONTENT" ]; }; then
-  log_error "Both -r|--role and -c|--content argument are required"
+  log error "Both -r|--role and -c|--content argument are required"
   exit 1
 fi
 
 if [ -n "$FILE_PATH" ] && [ ! -f "$FILE_PATH" ]; then
-  log_error "file $FILE_PATH not found"
+  log error "file $FILE_PATH not found"
   exit 2
 fi
 
@@ -133,7 +125,7 @@ else
 fi
 
 if [ -n "$DEBUG" ]; then
-  log_info "Appending message to conversation"
+  log info "Appending message to conversation"
 fi
 
 cat | jq \
diff --git a/lib/prompt/build b/lib/prompt/build
--- a/lib/prompt/build
+++ b/lib/prompt/build
@@ -55,11 +55,14 @@
 # SEE ALSO
 #  jq(1)
 
-# ╭───┤ Traps & Signals
+# ╭───┤ Bootstrap
 # ╰─
 
 # shellcheck source=../_fn/trap-debug
 . "$SH41_LIB/_fn/trap-debug"
+
+# log config
+export LOG_NAMESPACE="$SH41_ICON sh41-prompt-build"
 
 # ╭───┤ Global variables
 # ╰─
@@ -72,10 +75,6 @@ OUTPUT_CONVERSATION="{
 
 # ╭───┤ Functions
 # ╰─
-
-log_error() {
-  log --type error "$@" "sh41-prompt-build"
-}
 
 # Interpolate the given key with a value in the global $INPUT_PROMPT.
 #
@@ -111,7 +110,7 @@ is_valid_key() {
 # ╰─
 
 if [ -z "$INPUT_PROMPT" ]; then
-  log_error "No prompt provided, expected via stdin"
+  log error "No prompt provided, expected via stdin"
   exit 1
 fi
 
@@ -124,12 +123,12 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         file_path="$2"; shift
       else
-        log_error "-f|--file flag requires a value"
+        log error "-f|--file flag requires a value"
         exit 1
       fi
 
       if [ ! -f "$file_path" ]; then
-        log_error "-f|--file $file_path not found"
+        log error "-f|--file $file_path not found"
         exit 2
       fi
 
@@ -140,12 +139,12 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         key=$2; shift
       else
-        log_error "--var flag requires a key"
+        log error "--var flag requires a key"
         exit 1
       fi
 
       if ! is_valid_key "$key"; then
-        log_error "Invalid key name \"$key\". Keys must be alphanumeric, start with a letter and contain only underscores and hyphens"
+        log error "Invalid key name \"$key\". Keys must be alphanumeric, start with a letter and contain only underscores and hyphens"
         exit 1
       fi
 
@@ -162,7 +161,7 @@ while [ "$#" -gt 0 ]; do
       fi
     ;;
     --) shift; break ;;
-    -?*) log_error "unknown flag $1"; exit 1 ;;
+    -?*) log error "unknown flag $1"; exit 1 ;;
     *) break ;;
   esac
   shift
diff --git a/lib/providers/openai b/lib/providers/openai
--- a/lib/providers/openai
+++ b/lib/providers/openai
@@ -49,42 +49,35 @@
 # SEE ALSO
 #  curl(1), jq(1)
 
-# ╭───┤ Dependency check
-# ╰─ 
-
-if [ -z "$OPENAI_API_KEY" ]; then
-  log_error "missing required environment variable OPENAI_API_KEY"
-  exit 1
-fi
-
-if ! command -v "jq" >/dev/null 2>&1; then
-  log_error "jq is required to run this script"
-  exit 2
-fi
-
-if ! command -v "curl" >/dev/null 2>&1; then
-  log_error "curl is required to run this script"
-  exit 2
-fi
-
-# ╭───┤ Traps & Signals
+# ╭───┤ Bootstrap
 # ╰─
 
 # shellcheck source=../_fn/trap-debug
 . "$SH41_LIB/_fn/trap-debug"
 
+# log config
+export LOG_NAMESPACE="$SH41_ICON sh41-prompt-validate"
+
+# ╭───┤ Dependency check
+# ╰─ 
+
+if [ -z "$OPENAI_API_KEY" ]; then
+  log error "missing required environment variable OPENAI_API_KEY"
+  exit 1
+fi
+
+if ! command -v "jq" >/dev/null 2>&1; then
+  log error "jq is required to run this script"
+  exit 2
+fi
+
+if ! command -v "curl" >/dev/null 2>&1; then
+  log error "curl is required to run this script"
+  exit 2
+fi
+
 # ╭───┤ Functions
 # ╰─
-
-CMD_NAME="$SH41_ICON sh41-provider-openai"
-
-log_error() { 
-  log --type error "$@" "$CMD_NAME"
-}
-
-log_info() { 
-  log --type info "$@" "$CMD_NAME"
-}
 
 # Extract the content from the streamed response chunks.
 # - When streaming, OpenAI sends multiple JSON objects with the content of the
@@ -173,7 +166,7 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         max_tokens=$2; shift
       else
-        log_error "-mt|--max-tokens requires a value." >&2
+        log error "-mt|--max-tokens requires a value." >&2
         exit 3
       fi
     ;;
@@ -181,7 +174,7 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         temperature=$2; shift
       else
-        log_error "-t|--temperature requires a value." >&2
+        log error "-t|--temperature requires a value." >&2
         exit 3
       fi
     ;;
@@ -189,12 +182,12 @@ while [ "$#" -gt 0 ]; do
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
         model=$2; shift
       else
-        log_error "-m|--model requires a value." >&2
+        log error "-m|--model requires a value." >&2
         exit 3
       fi
     ;;
     --) shift; break ;;
-    -?*) log_error "Unknown flag: $1" >&2; exit 153 ;;
+    -?*) log error "Unknown flag: $1" >&2; exit 153 ;;
     *) break ;;
   esac
   shift
@@ -213,10 +206,10 @@ else
 fi
 
 if [ -n "$is_debug" ]; then 
-  log_info "should_stream: $should_stream"
-  log_info "should_output_raw: $should_output_raw"
-  log_info "temperature: $temperature"
-  log_info "model: $model"
+  log info "should_stream: $should_stream"
+  log info "should_output_raw: $should_output_raw"
+  log info "temperature: $temperature"
+  log info "model: $model"
 fi
 
 curl_stderr_tmp=$(mktemp -t sh41_openai-send_stderr-XXXXXX)
@@ -257,6 +250,6 @@ mutate < /dev/stdin \
     fi
 
 if [ "$(cat "$curl_exit_code_tmp")" -ne 0 ]; then
-  log_error "$(cat "$curl_stderr_tmp")"
+  log error "$(cat "$curl_stderr_tmp")"
   exit 4
 fi
