feat: add installation and initialization scripts
Additions:
- Implement `install.sh` script for cloning the repository, detecting shell rc file, and initializing configuration
- Add `.env-example` and `.sh41rc` template files for user configuration
- Update `load.sh` script to source user-specific configuration files
- Enhance `lib/config/init` and `lib/db/init` scripts for better error handling and user feedback

diff --git a/lib/config/init b/lib/config/init
--- a/lib/config/init
+++ b/lib/config/init
@@ -7,14 +7,35 @@
 #  init [-hc|--health-check]
 #
 # ENVIRONMENT
-#  SH41_CONFIG
+#  SH41_CONFIG_HOME
+#   Path to user's SH41 config directory.
+#
+#  SH41_CONFIG_RC 
 #   Path to user's SH41 config file.
 #
 #  SH41_LIB
 #   Path to SH41 internal lib directory.
 #
-#  SH41_ICON
-#   SH41 logo icon.
+# SEE ALSO
+#  fc-match(1)
+
+# ╭───┤ Shield wall!
+# ╰─
+
+if [ -z "$SH41_CONFIG_HOME" ]; then
+  log error -v var_name "\$SH41_CONFIG_HOME" "Missing environment variable"
+  exit 1
+fi
+
+if [ -z "$SH41_CONFIG_RC" ]; then
+  log error -v var_name "\$SH41_CONFIG_RC" "Missing environment variable"
+  exit 1
+fi
+
+if [ -z "$SH41_LIB" ]; then
+  log error -v var_name "\$SH41_LIB" "Missing environment variable"
+  exit 1
+fi
 
 # ╭───┤ Bootstrap
 # ╰─
@@ -29,31 +50,35 @@ export LOG_NAMESPACE=" init"
 # ╰─
 
 check_user() {
-  if [ ! -e "$SH41_CONFIG" ]; then
-    log error -v path "$SH41_CONFIG" "Config file not found"
+  if [ ! -e "$SH41_CONFIG_RC" ]; then
+    log error -v "\$SH41_CONFIG_RC" "$SH41_CONFIG_RC" "Config file not found"
     return 2
   fi
 
-  log success -v path "$SH41_CONFIG" "Config file exists"
+  log success -v "\$SH41_CONFIG_RC" "$SH41_CONFIG_RC" "Config file exists"
 }
 
 configure_user() {
-  mkdir -p "$(dirname "$SH41_CONFIG")"
-  cp "$SH41_HOME"/rc.sh "$SH41_CONFIG"
+  mkdir -p "$(dirname "$SH41_CONFIG_RC")"
 
-  if [ -e "$SH41_CONFIG" ]; then 
-    log success -v path "$SH41_CONFIG" "Config file created"
+  cp "$SH41_HOME"/.sh41rc "$SH41_CONFIG_RC"
+  cp "$SH41_HOME"/.env-example "$SH41_CONFIG_HOME/.env"
+  echo ".env" > "$SH41_CONFIG_HOME/.gitignore"
+
+  if [ -e "$SH41_CONFIG_RC" ]; then 
+    log success -v "\$SH41_CONFIG_RC" "$SH41_CONFIG_RC" "Config files created"
   fi
 }
 
 check_emoji_support() {
   font_name=$(fc-match monospace | awk -F '"' '{print $2}')
 
-  if echo "$font_name" | grep -q "Nerd"; then
-    log success -v font "$font_name" "Nerd font detected 󰱲"
-  else
-    log warn -v font "$font_name" "Nerd font not detected, some icons may not render correctly"
+  if ! echo "$font_name" | grep -q "Nerd"; then
+    log warn -v font "$font_name" \
+      "Nerd font not detected, some icons may not render correctly"
   fi
+
+  log success -v font "$font_name" "Nerd font detected 󰱲"
 }
 
 check_dependencies() {
@@ -66,7 +91,9 @@ check_dependencies() {
   done
 
   if [ -z "$has_error" ]; then
-    log success -v dependencies "$dependencies" "All dependencies installed"
+    log success \
+      -v dependencies "$dependencies" \
+      "All dependencies installed"
   fi
 }
 
diff --git a/lib/db/init b/lib/db/init
--- a/lib/db/init
+++ b/lib/db/init
@@ -17,11 +17,16 @@
 #  SH41_LIB
 #   Path to SH41 internal lib directory.
 #
-#  SH41_ICON
-#   SH41 logo icon.
-#
 # ERRORS
 #  1: Invalid input - parsing error of stdin, argument or flag parsing
+
+# ╭───┤ Shield wall!
+# ╰─
+
+if [ -z "$SH41_LIB" ]; then
+  log error -v var_name "\$SH41_LIB" "Missing environment variable"
+  exit 1
+fi
 
 # ╭───┤ Bootstrap
 # ╰─
@@ -39,13 +44,13 @@ check_sqlite() {
   if [ ! -e "$SH41_DB_CONNECTION" ]; then
     log error \
       -v "\$SH41_DB_CONNECTION" "$SH41_DB_CONNECTION" \
-      "DB file does not exist"
+      "DB does not exist"
     return 2
   fi
 
   log success \
     -v "\$SH41_DB_CONNECTION" "$SH41_DB_CONNECTION" \
-    "DB file exists"
+    "DB exists"
 }
 
 configure_sqlite() {
@@ -55,20 +60,20 @@ configure_sqlite() {
   if [ ! -e "$SH41_DB_CONNECTION" ]; then
     log error \
       -v "\$SH41_DB_CONNECTION" "$SH41_DB_CONNECTION" \
-      "DB file could not be created"
+      "DB could not be created"
     return 2
   fi
 
   log success \
     -v "\$SH41_DB_CONNECTION" "$SH41_DB_CONNECTION" \
-    "DB file created"
+    "DB created"
 }
 
 test_sqlite() {
   if ! sqlite3 "$SH41_DB_CONNECTION" "SELECT name FROM sqlite_master" > /dev/null 2>&1; then
     log error \
       -v "\$SH41_DB_CONNECTION" "$SH41_DB_CONNECTION" \
-      "DB file exists but sqlite3 cannot read it"
+      "DB exists but sqlite3 cannot read it"
     exit 2
   fi
 
@@ -115,12 +120,14 @@ done
 
 case "$SH41_DB_TYPE" in
   sqlite)
+    log info -v "\$SH41_DB_TYPE" "$SH41_DB_TYPE" "Sqlite database detected"
     if ! check_sqlite; then
       [ -n "$SHOULD_INIT" ] && configure_sqlite || exit 2
     fi
     test_sqlite
   ;;
   postgres)
+    log info -v "\$SH41_DB_TYPE" "$SH41_DB_TYPE" "Postgres database detected"
     if ! check_postgres; then
       [ -n "$SHOULD_INIT" ] &&  configure_postgres || exit 2
     fi
@@ -128,10 +135,10 @@ case "$SH41_DB_TYPE" in
   ;;
   *)
     log error \
-      -v "\$SH41_DB" "$SH41_DB" \
+      -v "\$SH41_DB_TYPE" "$SH41_DB_TYPE" \
       -v supported_type "sqlite, postgres" \
-      -v "\$SH41_CONFIG" "$SH41_CONFIG" \
-      "Invalid type, update \$SH41_DB variable in \$SH41_CONFIG file"
+      -v "\$SH41_CONFIG_RC" "$SH41_CONFIG_RC" \
+      "Invalid type, update \$SH41_DB variable in \$SH41_CONFIG_RC file"
     exit 2
   ;;
 esac
