feat: add `LOG_LEVEL` functionality to control message verbosity
Updates:
- Introduce `LOG_LEVEL` environment variable to filter messages by severity
- Default `LOG_LEVEL` to "error" if not set

diff --git a/lib/_scripts/log b/lib/_scripts/log
--- a/lib/_scripts/log
+++ b/lib/_scripts/log
@@ -9,26 +9,39 @@
 # FLAGS
 #  [-ns|--no-color]
 #   Do not print colors or icons.
+#   Defaults to true if the CI environment variable is set, otherwise false.
 #
 # OPTIONS
 #  [-v|--var <name> <value>]
-#   Print a variable name and its value after the message text.
+#   Print a variable name and its value, nicely formatted and color coded,
+#   after the message text.
 #
 # ARGUMENTS
-#  <type=error>
+#  <type>
 #   The type of message to print. Possible values are "error", "warning",
-#   "info", and "success". Default is "error".
+#   "info", and "success".
 #
 #  <message>
 #   The message to print. Can be passed as the first argument or as 
 #   standard input.
 #
 # ENVIRONMENT
+#  LOG_LEVEL
+#   The minimum level of log messages to print. Possible values are "error",
+#   "warning" and "info" ("success" messages will always be printed).
+#   Defaults to "error".
+#
 #  LOG_NAMESPACE
 #   If set, the namespace is printed before the message.
 #
 #  CI
-#   If exists, the message is printed without colors.
+#   If set, messages are printed without colors.
+
+# ╭───┤ Bootstrap
+# ╰─
+
+LOG_NAMESPACE=${LOG_NAMESPACE:-}
+LOG_LEVEL=${LOG_LEVEL:-error}
 
 # ╭───┤ Functions
 # ╰─
@@ -59,10 +72,28 @@ log_with_style() {
   echo "$(date +%T) $styled_type_label $styled_namespace$1 $2"
 }
 
+should_print() {
+  case $LOG_LEVEL in
+    err|error) [ "$1" = "error" ] || [ "$1" = "err" ] || [ "$1" = "success" ] ;;
+    warn|warning) [ "$1" = "error" ] || [ "$1" = "err" ] || [ "$1" = "warning" ] || [ "$1" = "warn" ] || [ "$1" = "success" ] ;;
+    info) [ "$1" = "error" ] || [ "$1" = "err" ] || [ "$1" = "warning" ] || [ "$1" = "warn" ] || [ "$1" = "info" ] || [ "$1" = "success" ] ;;
+  esac
+}
+
 # ╭───┤ Argument parsing
 # ╰─
 
-message_type=${1:-error}; shift
+message_type=$1; 
+if [ -z "$message_type" ]; then
+  echo "No message type provided" >&2
+  exit 1
+fi
+shift
+
+if ! should_print "$message_type"; then
+  exit 0
+fi
+
 has_color=$([ -n "$CI" ] && echo "" || echo "true")
 variables=""
 
@@ -70,14 +101,14 @@ while [ "$#" -gt 0 ]; do
   case $1 in
     -nc|--no-color) has_color=""; shift ;;
     -v|--var)
-      if [ "$2" ] && [ "${2#-}" = "$2" ]; then
+      if [ "$2" ]; then
         key=$2; shift
       else
-        echo "-v|--var flag requires a key" >&2
+        echo "-v|--var option requires a key" >&2
         exit 1
       fi
 
-      if [ "${2#-}" = "$2" ]; then
+      if [ "$2" ]; then
         value="$2"; shift
       fi
 
@@ -88,6 +119,8 @@ while [ "$#" -gt 0 ]; do
       fi
       shift
     ;;
+    --) shift; break ;;
+    -*) echo "Unknown parameter $1" >&2; exit 1 ;;
     *) break ;;
   esac
 done
